import pandas as pd

output_file = r'D:\IGS\PB Data Utils Scripts\item_replaced_with_default_into_excel\output\output_file.xlsx'

item_list = ['Gang box (4 + 3)', 'S.S. Commender ', 'Gang box (4 + 3)', 'Binding wire', 'Weighing Charge (Rod)', 'Bore Clamp  (1 1/4 " X 1")', 'Jet Valayam', 'Surya Cem ', 'Binding wire', 'Nanganallur Talk', 'Nanganallur Talk', 'Tee [GI]  (1" X 1/2" ) ', 'Bar Nipple [GI] (1") ', 'Pipe Nipple [GI] (1"  x  6" ) ', 'Pipe Nipple [GI] (1/2 X 6)', 'Hose [Green] (3/4" )', 'Gang box (4 + 4)', 'Nanganallur Talk', 'S.S. Commender ', 'Hose [Green] (3/4" )', 'Binding wire', 'Nanganallur Talk', 'Nanganallur Talk', 'Binding wire', 'Binding wire', 'Advertisement', 'Indian Closet With P Trap', 'Nanganallur Talk', 'Nanganallur Talk', 'Nanganallur Talk', 'Weighing Charge (Rod)', 'Nanganallur Talk', 'Binding wire', 'Binding wire', 'Motor reapair', 'Gang box (4 + 4)', 'Binding wire', 'Nanganallur Talk', 'Nanganallur Talk', 'Nanganallur Talk', 'Nanganallur Talk', 'Binding wire', 'Nanganallur Talk', 'Nanganallur Talk', 'End Cap [PVC] (1") || (32 mm)', 'End Cap [PVC] (1 1/2")', 'U clamp with washer  [4" & 2 1/2" & 1"]', 'Binding wire', 'Gang box (4 + 4)', 'LED Tube Light [24 W] [Philips]', 'Nanganallur Talk', 'Bar Angle 30"', 'Bar Angle 24"', 'Bar Angle 18"', 'Bar Angle 12"', 'Bar Angle 9"', 'Bar Angle 6"', 'U clamp with washer  [1" & 1 1/2" & 2" & 2 1/2 & 4]', 'Anchor Fastner Boltnut (8mm)', 'Axe Saw Blade [Double]', 'Nanganallur Talk', 'Nanganallur Talk', 'Wood Box 10 x 8 ', 'End Cap [CPVC] (1/2")', 'End Cap [PVC] (1") || (32 mm)', 'Teak Wood [Second Quality ]', 'Bathroom Frame [WPC] [4 x 2.5]', 'Teak Wood [Second Quality ]', 'Bathroom Frame [WPC] [4 x 2.5]', 'Nanganallur Talk', 'Axe Saw Blade [Double]', 'Tube Level Hose ', 'Nanganallur Talk', 'Coaches Screw (2" x 10)', 'GI Pipe 5 feet', 'Nanganallur Talk', 'LED Fittings [20 W]', 'Wire 1 sq.mm (90 mtr)', 'Nanganallur Talk', 'Nanganallur Talk', 'Bath Room Area Water Proofing', 'Over Head Tank', 'Bar Angle 18"', 'Bar Angle 9"', 'Bolt Nut Washer (1")', 'FTA [PVC] (1" )', 'Discount', 'cerabond', 'Nanganallur Talk', 'Isolator 4 pole (63 A)', 'GI Pipe 5 feet', 'Nanganallur Talk', 'Nanganallur Talk', 'Gully Trap [ ASH - SWR] (110 X 110)', 'Discount', 'Nanganallur Talk', 'Nanganallur Talk', 'Nanganallur Talk', 'Nanganallur Talk', '8558 Ultima', '8751 Ultima ',
             '0419 Ultima ', '8231 Ultima ', 'TRAVALLING EXPENSE', 'Switch with indicator 16A 1 way', 'Bell switch', 'Telephone Jack (Rj 11)', 'Plug Top (15 Ams)', 'Gate and Fixed Grill', 'cerabond', 'Indian Closet With P Trap', '8558 Ultima', '8231 Ultima ', '0419 Ultima ', '8571 ULTIMA', 'Ring (7"X7") &(7"X3")', 'Metal plate 4 model(Remo)', 'Pipe [holder] (6")', '8571 ULTIMA', 'Advertisement', 'Saddle  [PVC] (4 X 1/2 )', 'FTA  [PVC] (1/2")', 'FTA [PVC] (1" x 1/2")[Bross]', 'Hose ( 1/2 " )', 'Steps Granite [Brown Labota]', 'Bolt Nut Washer (2")', 'Advertisement', '0470 - Tractor Emelson ', '0615 - Tractor Emelson ', '8417 - Tracter Emulsion', 'Grill', 'cerabond', 'Coupling [PVC] (2 1/2" ) || (75 mm)', 'Hall Bedroom Floor [NEO MILTON BIANCO]  (2T)', 'Kitchen Wall Tile [Marcos Gris] ', 'Advertisement', 'Advertisement', 'Advertisement', 'Beta', 'Clamp (Bore) (1  " X 1/2 ")', 'Foundation Bolt Nut (6")', 'Oil', 'Araldite (10gm) Speed', 'Sliding Window (5.5 ft X 3 ft)', 'Indian Closet With P Trap', 'Star Drillbit', 'Ext. Nipple (2 1/2")', 'Compound Wall post', 'cerabond', 'Tap [PVC] ( 1/2 " )', 'Ext. Nipple (2 1/2")', 'PVC Door Plywood', 'Bib Cock Jade Long Body (G0206A1)', 'Crust Bath Spout With Diverter [G3128A1] (PARRY)', '8571 ULTIMA', '0419 Ultima ', '8558 Ultima', '8231 Ultima ', 'Multi-Flow hand Shower 100mm (T9983A1)', 'Focus Light (20w) LED ', 'Surya Cem (50 Kg)', 'Tap [PVC] ( 1/2 " )', 'Rag Bolt [C8083]', 'Wash Basin [Kolar] Wall Hung (18x13) (C042E1C)', 'Tap [PVC] ( 1/2 " )', 'Hinges (EPCO Heal)', 'Pipe Gate', 'Koches Screw', 'Balcony And Angle', 'FTA [PVC] (1" )', 'Main Door (6 1/2ft X 3ft) with Design', 'Main Door 6 1/2 X 3f (Teak pannel)', 'Main Door 6 1/2 X 3f (Teak pannel)', 'Flush Door', 'Reeper (1.5 x1)', 'Reeper 3 X 1 (7 feet)', '0643 Enamel', 'Pipe (5" X 5 " )', 'POP', 'Automatic Motor System Fixing', 'Ceramic Board', 'GenSet', 'Main Door [ 6.5 x 3] [Carved - Teak]', 'Bolt Nut ( 1 3/4" X 1/4 ") ', 'Main Door 6 1/2 X 3f (Teak pannel)', 'Bedroom Door [HDHMR] [6 3/4 x 2 3/4]', 'Bedroom Door [HDHMR] [6 3/4 x 2 3/4]', 'Bedroom Door [HDHMR] [6 3/4 x 2 1/4]', 'Bathroom Door [WPC] (6.75 X 2.25)', 'Reeper 3 X 1 (7 feet)', 'Main Door [6.75 X 2.91]', 'laminated door(6.75 x 2.75)']

df = pd.DataFrame(item_list, columns=['Item Name'])


df.to_excel(output_file)

print('Successfully created the output file')
